# Redis配置
spring:
  redis:
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-wait: 6000ms
        max-idle: 8
    timeout: 500
  # 数据库驱动：
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #数据库连接词Druid
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #连接池配置
      # 初始化连接池的连接数量 大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时时间
      max-wait: 60000
      #配置间隔多久进行检测，检测需要关闭的空闲连接，单位毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中的最小生存时间
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 'X'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭   个人建议如果想用SQL防火墙 建议打开
      pool-prepared-statements: true
      #当值大于0时poolPreparedStatements会自动修改为true
      max-pool-prepared-statement-per-connection-size: 5000
      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      #合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      aop-patterns: com.zengkan.*.service.*

#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
# 分页插件
pagehelper:
  helper-dialect: mysql
  #
  reasonable: true
  support-methods-arguments: true
  params: count=countSql